#! /usr/bin/env bash

# have we done this?, then we should not do it again
if [ -n "$PRE_APPROUTER_PATH" ]; then
    echo "looks like we're already set... ignoring your request"
else
    echo "setting your environment up for you...."
    # capture how the path was before we started
    export PRE_APPROUTER_PATH=$PATH

    HERE=`pwd`
    ROOT=${HERE}/build_output
    export PATH=${ROOT}/bin:$PATH
    export PATH=${ROOT}/usr/local/ssl/bin/:$PATH
    export PATH=${ROOT}/sbin:$PATH

    function deactivate(){
        export PATH=$PRE_APPROUTER_PATH
        unset PRE_APPROUTER_PATH
    }

    export -f deactivate
fi

