#! /usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/environment
ACTION=$1
if [ "${ACTION}x" == "x" ]; then
  for stop_ctl_file in ${RUNTIME_BIN_DIR}/stop*;
  do
    ${stop_ctl_file}
  done
  ${DIR}/status
elif [ "$ACTION" == "flush" ]; then
  rm ${RUN_DIR}/*
elif [ "$ACTION" == "prod" ]; then
  perpctl D instance1
  perpctl D instance2
elif [ "$ACTION" == "perp" ]; then
  # we do expect to own the machine, so this is
  # reasonable
  killall perpd
else
  perpctl D ${ACTION}
fi
