#! /usr/bin/env bash

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${MY_DIR}/environment

# switch the prod config link from the one it's currently set
# to, to the other
if [ ${NGINX_ACTIVE_CONFIG} == ${NGINX_CONF_FILE_1} ]; then
  ln -sf ${NGINX_CONF_FILE_2} ${NGINX_CONF_LINK}
fi
if [ ${NGINX_ACTIVE_CONFIG} == ${NGINX_CONF_FILE_2} ]; then
  ln -sf ${NGINX_CONF_FILE_1} ${NGINX_CONF_LINK}
fi
# forcing a reload of the nginx config, causing a graceful
# 'roll' from the old instance to the new
kill -HUP `cat ${NGINX_PIDFILE}`
